version: '3.8'

services:
  # Servidor de reconstrução de imagens
  servidor:
    build: .
    ports:
      - "5000:5000"
    command: servidor
    volumes:
      - ./Dados:/app/Dados
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/desempenho"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  # Cliente para envio de sinais
  cliente:
    build: .
    depends_on:
      - servidor
    command: cliente
    volumes:
      - ./Dados:/app/Dados
      - ./resultados:/app/resultados
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
    
volumes:
  resultados: